<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="Kho Dữ liệu và Hệ thống Hỗ trợ Quyết định (DW &amp; DSS)">
    <node ID="node_1" TEXT="Giới thiệu">
      <node ID="node_6" TEXT="Tổng quan">
        <node ID="node_25" TEXT="Nền tảng cho DSS và BI hiện đại">
        </node>
        <node ID="node_26" TEXT="Trung tâm môi trường dữ liệu có kiến trúc">
        </node>
        <node ID="node_27" TEXT="Nền tảng xử lý thông tin DSS">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="1. Khái niệm cơ bản về kho dữ liệu">
      <node ID="node_7" TEXT="Khái niệm Inmon Wiley">
        <node ID="node_28" TEXT="Tập hợp dữ liệu định hướng chủ đề">
        </node>
        <node ID="node_29" TEXT="Tích hợp">
        </node>
        <node ID="node_30" TEXT="Không biến đổi (Nonvolatile)">
        </node>
        <node ID="node_31" TEXT="Biến thiên theo thời gian (Time-variant)">
        </node>
        <node ID="node_32" TEXT="Hỗ trợ ra quyết định quản lý">
        </node>
      </node>
      <node ID="node_8" TEXT="4 Đặc trưng cốt lõi">
        <node ID="node_33" TEXT="Subject-oriented (Định hướng theo chủ đề)">
          <node ID="node_102" TEXT="Tổ chức quanh chủ đề phân tích">
          </node>
          <node ID="node_103" TEXT="Ví dụ: Bảo hiểm (khách hàng, hợp đồng), Sản xuất (sản phẩm, đơn hàng), Bán lẻ (sản phẩm, giao dịch)">
          </node>
        </node>
        <node ID="node_34" TEXT="Integrated (Tích hợp)">
          <node ID="node_104" TEXT="Từ nhiều nguồn khác nhau (ERP, CRM, Excel)">
          </node>
          <node ID="node_105" TEXT="Quá trình ETL: Chuyển đổi, Chuẩn hóa, Tổng hợp, Đồng nhất mã hóa">
          </node>
          <node ID="node_106" TEXT="Tạo “một bức tranh dữ liệu thống nhất”">
          </node>
        </node>
        <node ID="node_35" TEXT="Nonvolatile (Không biến đổi)">
          <node ID="node_107" TEXT="Chỉ Load và Access">
          </node>
          <node ID="node_108" TEXT="Không Update/Delete thường xuyên">
          </node>
          <node ID="node_109" TEXT="Lợi ích: Tăng ổn định, Đáng tin cậy, Hỗ trợ phân tích lịch sử">
          </node>
        </node>
        <node ID="node_36" TEXT="Time-variant (Biến thiên theo thời gian)">
          <node ID="node_110" TEXT="Dữ liệu gắn với yếu tố thời gian">
          </node>
          <node ID="node_111" TEXT="Lưu dữ liệu lịch sử nhiều năm">
          </node>
          <node ID="node_112" TEXT="Hỗ trợ phân tích xu hướng, dự báo">
          </node>
          <node ID="node_113" TEXT="Ví dụ: Doanh thu quý 3 trong 5 năm, Xu hướng hành vi khách hàng">
          </node>
        </node>
      </node>
      <node ID="node_9" TEXT="Đặc tính mở rộng khác">
        <node ID="node_37" TEXT="Granularity (Độ chi tiết dữ liệu)">
          <node ID="node_114" TEXT="Mức độ chi tiết/tổng hợp">
          </node>
          <node ID="node_115" TEXT="Chi tiết: linh hoạt, dung lượng lớn">
          </node>
          <node ID="node_116" TEXT="Thực tế: Lưu song song chi tiết và tổng hợp">
          </node>
        </node>
        <node ID="node_38" TEXT="Partitioning (Phân vùng dữ liệu)">
          <node ID="node_117" TEXT="Chia nhỏ dữ liệu">
          </node>
          <node ID="node_118" TEXT="Theo thời gian, địa lý, sản phẩm">
          </node>
          <node ID="node_119" TEXT="Cải thiện tốc độ truy vấn, quản trị">
          </node>
        </node>
        <node ID="node_39" TEXT="Homogeneity vs. Heterogeneity">
          <node ID="node_120" TEXT="Xử lý dữ liệu đồng nhất và dị thể">
          </node>
          <node ID="node_121" TEXT="Ví dụ: từ CRM, ERP, Excel, Web logs">
          </node>
        </node>
        <node ID="node_40" TEXT="Auditing (Kiểm toán dữ liệu)">
          <node ID="node_122" TEXT="Theo dõi nguồn gốc, biến đổi dữ liệu">
          </node>
          <node ID="node_123" TEXT="Đảm bảo minh bạch, tin cậy, tuân thủ">
          </node>
        </node>
      </node>
      <node ID="node_10" TEXT="Ý nghĩa thực tiễn">
        <node ID="node_41" TEXT="Một phiên bản duy nhất của sự thật">
        </node>
        <node ID="node_42" TEXT="Nền tảng cho BI/Analytics">
        </node>
        <node ID="node_43" TEXT="Khả năng phân tích dài hạn, đa chiều">
        </node>
        <node ID="node_44" TEXT="Chuyển đổi từ Data → Information → Knowledge → Decision">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="2. Kiến trúc kho dữ liệu">
      <node ID="node_11" TEXT="Dẫn nhập">
        <node ID="node_45" TEXT="Tối ưu cho phân tích (OLAP)">
        </node>
        <node ID="node_46" TEXT="Mô hình hóa theo kiến trúc đa chiều">
        </node>
        <node ID="node_47" TEXT="Các kiến trúc phổ biến: Star, Snowflake, Galaxy Schema">
        </node>
        <node ID="node_48" TEXT="Dựa trên Fact Table và Dimension Table">
        </node>
      </node>
      <node ID="node_12" TEXT="Star Schema (Sơ đồ Ngôi sao)">
        <node ID="node_49" TEXT="Mô hình phổ biến">
        </node>
        <node ID="node_50" TEXT="Fact Table ở trung tâm (số liệu định lượng)">
        </node>
        <node ID="node_51" TEXT="Dimension Tables bao quanh (dữ liệu mô tả)">
        </node>
        <node ID="node_52" TEXT="Quan hệ 1-n giữa Fact và Dimension">
        </node>
        <node ID="node_53" TEXT="Đặc điểm">
          <node ID="node_124" TEXT="Đơn giản, dễ hiểu">
          </node>
          <node ID="node_125" TEXT="Hiệu suất truy vấn cao (dimension phi chuẩn hoá)">
          </node>
          <node ID="node_126" TEXT="Dư thừa dữ liệu (do phi chuẩn hoá)">
          </node>
          <node ID="node_127" TEXT="Phù hợp cho OLAP, báo cáo doanh nghiệp">
          </node>
        </node>
        <node ID="node_54" TEXT="Ví dụ">
          <node ID="node_128" TEXT="Fact_Sales (Date_ID, Product_ID, Sales_Amount)">
          </node>
          <node ID="node_129" TEXT="Dim_Date (ngày, tháng, quý, năm)">
          </node>
          <node ID="node_130" TEXT="Dim_Product (tên, loại, nhà sản xuất)">
          </node>
        </node>
      </node>
      <node ID="node_13" TEXT="Snowflake Schema (Sơ đồ Bông tuyết)">
        <node ID="node_55" TEXT="Dimension Tables được chuẩn hoá">
        </node>
        <node ID="node_56" TEXT="Nhiều bảng con liên kết">
        </node>
        <node ID="node_57" TEXT="Cấu trúc">
          <node ID="node_131" TEXT="Fact Table ở trung tâm">
          </node>
          <node ID="node_132" TEXT="Dimension Tables chuẩn hóa nhiều cấp">
          </node>
          <node ID="node_133" TEXT="Liên kết trực tiếp/gián tiếp qua khóa ngoại">
          </node>
        </node>
        <node ID="node_58" TEXT="Đặc điểm chính">
          <node ID="node_134" TEXT="Dimension normalized">
          </node>
          <node ID="node_135" TEXT="Giảm dư thừa dữ liệu">
          </node>
          <node ID="node_136" TEXT="Tăng tính toàn vẹn dữ liệu">
          </node>
        </node>
        <node ID="node_59" TEXT="Ưu điểm">
          <node ID="node_137" TEXT="Tiết kiệm dung lượng">
          </node>
          <node ID="node_138" TEXT="Dễ bảo trì, cập nhật">
          </node>
          <node ID="node_139" TEXT="Hữu ích cho dimension lớn">
          </node>
        </node>
        <node ID="node_60" TEXT="Nhược điểm">
          <node ID="node_140" TEXT="Cấu trúc phức tạp">
          </node>
          <node ID="node_141" TEXT="Hiệu năng truy vấn chậm hơn (join nhiều bảng)">
          </node>
          <node ID="node_142" TEXT="Không thân thiện người dùng nghiệp vụ">
          </node>
          <node ID="node_143" TEXT="Dim_Product tách thành Dim_Product, Dim_Brand, Dim_Category">
          </node>
        </node>
      </node>
      <node ID="node_14" TEXT="Galaxy Schema (Sơ đồ Ngân hà / Fact Constellation)">
        <node ID="node_61" TEXT="Nhiều bảng Fact cùng chia sẻ Dimension chung">
          <node ID="node_144" TEXT="Phù hợp khi dữ liệu chiều có phân cấp phức tạp">
          </node>
          <node ID="node_145" TEXT="Nhiều Fact Table (bán hàng, vận chuyển, tồn kho)">
          </node>
          <node ID="node_146" TEXT="Dimension Tables chia sẻ (Dim_Time, Dim_Product)">
          </node>
          <node ID="node_147" TEXT="Kết hợp Star/Snowflake trong từng phần">
          </node>
          <node ID="node_148" TEXT="Tổ chức dữ liệu linh hoạt">
          </node>
          <node ID="node_149" TEXT="Fact Tables liên quan qua Dimension chung">
          </node>
          <node ID="node_150" TEXT="Phân tích liên miền (cross-functional)">
          </node>
          <node ID="node_151" TEXT="Hỗ trợ nhiều quy trình kinh doanh">
          </node>
        </node>
        <node ID="node_62" TEXT="Ví dụ minh họa (Siêu thị)">
          <node ID="node_157" TEXT="Fact_Sales, Fact_Inventory, Fact_Shipping">
          </node>
          <node ID="node_158" TEXT="Chia sẻ Dim_Time, Dim_Product, Dim_Store, Dim_Customer">
          </node>
          <node ID="node_152" TEXT="Giảm trùng lặp Dimension">
          </node>
          <node ID="node_153" TEXT="Mạnh mẽ phân tích đa chiều toàn diện">
          </node>
          <node ID="node_154" TEXT="Cấu trúc rất phức tạp">
          </node>
          <node ID="node_155" TEXT="Khó thiết kế và bảo trì">
          </node>
          <node ID="node_156" TEXT="Yêu cầu công cụ OLAP/BI tối ưu">
          </node>
          <node ID="node_159" TEXT="Bảng trung tâm mô hình đa chiều">
          </node>
          <node ID="node_160" TEXT="Chứa dữ liệu định lượng (measures/facts)">
          </node>
          <node ID="node_161" TEXT="Tham chiếu bởi khóa ngoại đến Dimension Table">
          </node>
        </node>
      </node>
      <node ID="node_15" TEXT="Fact Table (Bảng sự kiện)">
        <node ID="node_63" TEXT="Ví dụ minh họa (Fact_Sales)">
          <node ID="node_166" TEXT="Thuộc tính: Product_ID, Customer_ID, Time_ID, Store_ID">
          </node>
          <node ID="node_167" TEXT="Measures: Quantity_Sold, Sales_Revenue, Discount">
          </node>
          <node ID="node_162" TEXT="Khóa chính là khóa tổng hợp (Composite Key)">
          </node>
          <node ID="node_163" TEXT="Số lượng bản ghi rất lớn">
          </node>
          <node ID="node_164" TEXT="Dữ liệu mang tính lịch sử (time-variant)">
          </node>
          <node ID="node_165" TEXT="Facts thường additive hoặc semi-additive">
          </node>
        </node>
        <node ID="node_64" TEXT="Phân loại">
          <node ID="node_168" TEXT="Transaction Fact Table (từng giao dịch)">
          </node>
          <node ID="node_169" TEXT="Snapshot Fact Table (trạng thái tại thời điểm)">
          </node>
          <node ID="node_170" TEXT="Accumulating Fact Table (tiến trình nhiều giai đoạn)">
          </node>
        </node>
        <node ID="node_65" TEXT="Vai trò trong phân tích">
          <node ID="node_171" TEXT="Trung tâm chứa số liệu">
          </node>
          <node ID="node_172" TEXT="Tính toán chỉ số kinh doanh">
          </node>
          <node ID="node_173" TEXT="Kết hợp với Dimension để trả lời câu hỏi nghiệp vụ">
          </node>
          <node ID="node_174" TEXT="Mô tả ngữ cảnh cho Fact Table">
          </node>
          <node ID="node_175" TEXT="Chứa thuộc tính để phân tích, lọc, nhóm">
          </node>
          <node ID="node_176" TEXT="Ít bản ghi hơn Fact, nhiều thông tin mô tả">
          </node>
          <node ID="node_177" TEXT="Khóa chính liên kết với khóa ngoại Fact Table">
          </node>
          <node ID="node_178" TEXT="Chứa dữ liệu mô tả, định tính">
          </node>
          <node ID="node_179" TEXT="Thiết kế denormalized (ít chuẩn hóa)">
          </node>
          <node ID="node_180" TEXT="Có cấu trúc phân cấp (hierarchy) cho drill-down/roll-up">
          </node>
        </node>
      </node>
      <node ID="node_16" TEXT="Dimension Table (Bảng chiều)">
        <node ID="node_66" TEXT="Ví dụ kết hợp Fact &amp; Dimension">
          <node ID="node_187" TEXT="Fact_Sales + Dim_Time + Dim_Product → Doanh thu theo danh mục sản phẩm quý 1/2024">
          </node>
          <node ID="node_181" TEXT="Dimension_Product (Product_ID, Name, Category, Brand)">
          </node>
          <node ID="node_182" TEXT="Dimension_Time (Time_ID, Day, Month, Year, Holiday_Flag)">
          </node>
          <node ID="node_183" TEXT="Dimension_Customer (Customer_ID, Name, Age_Group, Location)">
          </node>
          <node ID="node_184" TEXT="Cung cấp ngữ cảnh cho số liệu">
          </node>
          <node ID="node_185" TEXT="Phân tích dữ liệu theo nhiều góc nhìn">
          </node>
          <node ID="node_186" TEXT="Thực hiện drill-down/roll-up trong OLAP">
          </node>
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="3. Các đặc tính về dữ liệu của kho dữ liệu">
      <node ID="node_17" TEXT="Chất lượng các chiều dữ liệu (Data Quality Dimensions)">
        <node ID="node_69" TEXT="Độ chính xác (Accuracy)">
          <node ID="node_188" TEXT="Dữ liệu phản ánh đúng thực tế">
          </node>
        </node>
        <node ID="node_70" TEXT="Tính đầy đủ (Completeness)">
          <node ID="node_189" TEXT="Không thiếu trường/giá trị quan trọng">
          </node>
        </node>
        <node ID="node_71" TEXT="Tính nhất quán (Consistency)">
          <node ID="node_190" TEXT="Dữ liệu thống nhất toàn hệ thống">
          </node>
        </node>
        <node ID="node_72" TEXT="Tính hợp lệ (Validity)">
          <node ID="node_191" TEXT="Tuân theo chuẩn mực, quy tắc">
          </node>
        </node>
        <node ID="node_73" TEXT="Tính kịp thời (Timeliness)">
          <node ID="node_192" TEXT="Dữ liệu cập nhật đúng lúc">
          </node>
        </node>
        <node ID="node_74" TEXT="Tính duy nhất (Uniqueness)">
          <node ID="node_193" TEXT="Không có dữ liệu trùng lặp">
          </node>
        </node>
        <node ID="node_75" TEXT="Tính dễ truy cập và khả dụng (Accessibility &amp; Availability)">
          <node ID="node_194" TEXT="Người dùng có quyền và công cụ để truy cập">
          </node>
        </node>
        <node ID="node_67" TEXT="Chất lượng dữ liệu (Data Quality Dimensions)">
        </node>
        <node ID="node_68" TEXT="Khác với 4 đặc tính của kho dữ liệu (Inmon)">
        </node>
      </node>
      <node ID="node_18" TEXT="Sự khác biệt">
        <node ID="node_76" TEXT="Đặc tính dữ liệu tổng quát (Data Quality Dimensions): đánh giá chất lượng dữ liệu">
        </node>
        <node ID="node_77" TEXT="Đặc trưng dữ liệu của kho dữ liệu (Inmon): nguyên lý thiết kế kiến trúc DW">
        </node>
      </node>
      <node ID="node_19" TEXT="So sánh">
        <node ID="node_78" TEXT="Mục tiêu">
          <node ID="node_195" TEXT="DQ: Đảm bảo dữ liệu chính xác, đầy đủ, hữu ích">
          </node>
          <node ID="node_196" TEXT="Inmon: Định hình cách tổ chức DW để phân tích">
          </node>
        </node>
        <node ID="node_79" TEXT="Độ chính xác">
          <node ID="node_197" TEXT="DQ: Phản ánh đúng thực tế">
          </node>
          <node ID="node_198" TEXT="Inmon: Tích hợp, chuẩn hóa đảm bảo tin cậy">
          </node>
        </node>
        <node ID="node_80" TEXT="Tính đầy đủ">
          <node ID="node_199" TEXT="DQ: Không thiếu sót dữ liệu">
          </node>
          <node ID="node_200" TEXT="Inmon: Time-variant, đảm bảo bức tranh toàn diện">
          </node>
        </node>
        <node ID="node_81" TEXT="Tính nhất quán">
          <node ID="node_201" TEXT="DQ: Không mâu thuẫn giữa các nguồn">
          </node>
          <node ID="node_202" TEXT="Inmon: &quot;Integrated&quot; loại bỏ mâu thuẫn">
          </node>
        </node>
        <node ID="node_82" TEXT="Tính hợp lệ">
          <node ID="node_203" TEXT="DQ: Tuân thủ quy tắc nghiệp vụ">
          </node>
          <node ID="node_204" TEXT="Inmon: Thiết kế schema chuẩn, kiểm tra trước khi nạp">
          </node>
        </node>
        <node ID="node_83" TEXT="Tính kịp thời">
          <node ID="node_205" TEXT="DQ: Dữ liệu sẵn sàng đúng thời điểm">
          </node>
          <node ID="node_206" TEXT="Inmon: &quot;Time-Variant&quot;, dữ liệu kèm dấu thời gian">
          </node>
        </node>
        <node ID="node_84" TEXT="Tính duy nhất">
          <node ID="node_207" TEXT="DQ: Không trùng lặp">
          </node>
          <node ID="node_208" TEXT="Inmon: ETL loại bỏ dữ liệu dư thừa">
          </node>
        </node>
        <node ID="node_85" TEXT="Khả năng truy cập">
          <node ID="node_209" TEXT="DQ: Người dùng dễ dàng khai thác">
          </node>
          <node ID="node_210" TEXT="Inmon: &quot;Nonvolatile&quot;, dữ liệu ổn định, chỉ đọc">
          </node>
        </node>
      </node>
    </node>
    <node ID="node_5" TEXT="4. Vấn đề về độ mịn dữ liệu">
      <node ID="node_20" TEXT="Khái niệm">
        <node ID="node_86" TEXT="Mức độ chi tiết/tổng hợp của dữ liệu">
        </node>
        <node ID="node_87" TEXT="Fine-grained (từng giao dịch)">
        </node>
        <node ID="node_88" TEXT="Coarse-grained (doanh thu theo tháng)">
        </node>
        <node ID="node_89" TEXT="Ảnh hưởng đến khả năng phân tích, dung lượng, hiệu suất">
        </node>
      </node>
      <node ID="node_21" TEXT="Lợi ích và thách thức">
        <node ID="node_90" TEXT="Lợi ích">
          <node ID="node_211" TEXT="Độ mịn chi tiết cao: phân tích sâu, drill-down">
          </node>
          <node ID="node_212" TEXT="Độ mịn tổng hợp: tiết kiệm không gian, truy vấn nhanh, báo cáo cấp cao">
          </node>
        </node>
        <node ID="node_91" TEXT="Thách thức">
          <node ID="node_213" TEXT="Mức chi tiết cao: dung lượng lớn, quản lý phức tạp">
          </node>
          <node ID="node_214" TEXT="Mức tổng hợp: hạn chế phân tích chi tiết">
          </node>
        </node>
      </node>
      <node ID="node_22" TEXT="Ví dụ minh họa">
        <node ID="node_92" TEXT="Chi tiết: giao dịch thẻ ATM (ngày, giờ, số tiền, địa điểm)">
        </node>
        <node ID="node_93" TEXT="Tổng hợp: tổng số tiền rút ATM theo ngày/tháng">
        </node>
        <node ID="node_94" TEXT="Ngân hàng lưu cả hai mức">
        </node>
      </node>
      <node ID="node_23" TEXT="Mô hình hai cấp độ (Dual Levels of Granularity)">
        <node ID="node_95" TEXT="Atomic data (dữ liệu gốc chi tiết nhất)">
        </node>
        <node ID="node_96" TEXT="Summary data (dữ liệu tóm tắt, tổng hợp)">
        </node>
        <node ID="node_97" TEXT="Cân bằng khả năng phân tích và hiệu quả tài nguyên">
        </node>
      </node>
      <node ID="node_24" TEXT="Ý nghĩa trong thiết kế kho dữ liệu">
        <node ID="node_98" TEXT="Quyết định quan trọng nhất khi thiết kế">
        </node>
        <node ID="node_99" TEXT="Thiết kế sai: quá nặng hoặc thiếu linh hoạt">
        </node>
        <node ID="node_100" TEXT="Giải pháp thực tế: đa cấp độ độ mịn (chi tiết &amp; tổng hợp)">
        </node>
        <node ID="node_101" TEXT="Ảnh hưởng đến hữu ích của DW, chi phí, hiệu năng">
        </node>
      </node>
    </node>
  </node>
</map>